### PR TITLE
Bump rubocop, configure new cops

### PR DESCRIPTION
**Pull request by juan-apa**
## Features
- Bump rubocop from 0.85 to 0.89.0
- Added missing config for new (and some existing) cops.
- Fixed some departments for existing cops config (Documentation, LineLength).

### CODE REVIEW

**Comment by JuannFerrari** [comment]
Very good addition! Although I think that **the new cops** has to be placed in `default_edge.yml`, not in `default.yml`. It may cause problems for people using a lower version of a rubocop such as 0.72

**Review by JuannFerrari — COMMENTED** [review]
Very good addition! Although I think that **the new cops** have to be placed in `default_edge.yml,` not in `default.yml`. It may cause problems for people using a lower version of a rubocop such as `0.72`

**Comment by juanmanuelramallo** [comment]
Agree with @JuannFerrari

**Review by JuannFerrari — APPROVED** [review]
🚀

**Comment by juan-apa** [comment]
Is it necesary to bump the gem version to 0.1.2? If it is, should it be done in this PR, or in a new one?

**Comment by JuannFerrari** [comment]
@juan-apa Yes, make a new PR for bump gem version

**Review by juanmanuelramallo — APPROVED** [review]

**Pull request merged**
